### ISSUE TITLE
Unable to compile "error: no such subcommand: `build-bpf`"

### ISSUE THREAD

**Issue by siulynot** [Bonfida/bonfida-bot-ui#3]
When i try to compile with "make" i get this: 

```
cargo build-bpf --manifest-path "third_party/serum_dex/dex/Cargo.toml" --bpf-out-dir target/deploy
error: no such subcommand: `build-bpf`
make: *** [Makefile:8: serum_dex.so] Error 101
root@3ba2e7f1e1fa:/bonfida-bot/program# /bin/sh: 1: cargo: not found
bash: /bin/sh:: No such file or directory
```

I assume it requires this package: https://crates.io/crates/solana-cargo-build-bpf/1.4.9 

The crates.io site says the package has been yanked.

When i try : ` cargo install solana-cargo-build-bp     `                                                                                                                                                 
  i get: 
```
  Updating crates.io index error: could not find `solana-cargo-build-bp` in registry `https://github.com/rust-lang/crates.io-index` with version `*` 
```
Please some help would be appreciated, thanks.

**Comment by dr497** [comment]
Hey! This is UI repo, I think you are looking for this repo https://github.com/Bonfida/bonfida-bot

**Comment by siulynot** [comment]
I actually want to use this repo, wanted to know if i can deploy it with my
own webhook url to execute orders from a server i own.

**Comment by siulynot** [comment]
Oh, sorry about that. Hehe
